services:
  db:
    container_name: db
    image: "mongo:latest"
    networks:
      - custom

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
    networks:
      - custom

  back:
    container_name: back
    build: chat_back/
#    ports:
#      - 0.0.0.0:5000:3001
    networks:
      - custom
    depends_on:
      - db

  python:
    container_name: python
    build: 2TenderHackTransformApi-main
    networks:
      - custom
    depends_on:
      - db

networks:
  custom:
    driver: bridge
